### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by germonprez** [sparrow217/CSCI4900001-github-repot#6]
Hi guys, 

I'm getting the following error when I try and run your issues.py

<img width="768" alt="screen shot 2017-04-06 at 9 11 11 am" src="https://cloud.githubusercontent.com/assets/656208/24758811/12145744-1aa9-11e7-9eef-fd850eb7d3ce.png">

and the msr14 db is set up: 

<img width="731" alt="screen shot 2017-04-06 at 9 13 17 am" src="https://cloud.githubusercontent.com/assets/656208/24758917/55b7611c-1aa9-11e7-8934-16ef1fff8083.png">

I simply ran your installation as you have posted on GH.

**Comment by jambunjo** [comment]
from the error it looks like you didn't run.
      sudo apt-get install python2.7-mysqldb
also in the code the connection string needs to be changed so it is using the correct user and database name.
      db = MySQLdb.connect("localhost","yourusername","yourpassword", "DatabaseName/msr14")
and there is a bug with the sql string.
      sqlQuery needs to be changed to sql

**Comment by germonprez** [comment]
Ok working. I recommend that you update your Install to get this squared away.
