### ISSUE TITLE
VMware Workstation 12 does not support MacOS [Installation]

### ISSUE THREAD

**Issue by hacksmath** [sparrow217/CSCI4900001-github-repot#8]
[VMware Workstation 12](https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_workstation_pro/12_0) linked to in the installation instructions only support Windows and Linux. I used [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) to proceed with the installation procedure, but if you'd like to stick with VMware across all platforms, a quick search revealed [VMware Fusion 8](https://my.vmware.com/en/web/vmware/info/slug/desktop_end_user_computing/vmware_fusion/8_0) as their Mac option. Perhaps you could look into adding that option for Mac users in your installation instructions.

**Comment by jambunjo** [comment]
Now has more generic install instructions.
